apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv
spec:
  capacity:
    storage: 5Gi  # Ajuste conforme necessário
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/wsl/shared-pv  # Ajuste conforme necessário
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Ajuste conforme necessário