apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  selector:
    app: keycloak
  type: ClusterIP
  ports:
  - name: keycloak-service
    port: 80 # porta do service
    targetPort: 8080 # porta do container
    protocol: TCP